/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.telasCadastro;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;
import jtextfields.Limitador;

/**
 *
 * @author julia
 */
public class TelaCadastroCompraV1 extends javax.swing.JFrame {

   /**
    * Creates new form FormModeloCadastros
    */
   public TelaCadastroCompraV1() {
      initComponents();
      qtdNumero1.setDocument(new Limitador(3));
      qtdNumero2.setDocument(new Limitador(3));
      qtdNumero3.setDocument(new Limitador(3));
      qtdNumero4.setDocument(new Limitador(3));
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      north = new javax.swing.JPanel();
      titulo = new javax.swing.JLabel();
      south = new javax.swing.JPanel();
      novo = new javax.swing.JButton();
      cancelar = new javax.swing.JButton();
      gravar = new javax.swing.JButton();
      buscar = new javax.swing.JButton();
      sair = new javax.swing.JButton();
      center = new javax.swing.JPanel();
      fornecedor = new javax.swing.JLabel();
      listaFornecedor = new javax.swing.JComboBox<>();
      qtdNumero4 = new javax.swing.JTextField();
      listaProduto4 = new javax.swing.JComboBox<>();
      quantidade4 = new javax.swing.JLabel();
      produto4 = new javax.swing.JLabel();
      produto3 = new javax.swing.JLabel();
      listaProduto3 = new javax.swing.JComboBox<>();
      qtdNumero3 = new javax.swing.JTextField();
      quantidade3 = new javax.swing.JLabel();
      botaoPago = new javax.swing.JButton();
      qtdNumero2 = new javax.swing.JTextField();
      quantidade2 = new javax.swing.JLabel();
      listaProduto2 = new javax.swing.JComboBox<>();
      produto2 = new javax.swing.JLabel();
      qtdNumero1 = new javax.swing.JTextField();
      quantidade1 = new javax.swing.JLabel();
      listaProduto1 = new javax.swing.JComboBox<>();
      produto1 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Formulário de Cadastro");
      setResizable(false);

      north.setBackground(new java.awt.Color(255, 204, 0));
      north.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      north.setPreferredSize(new java.awt.Dimension(700, 75));

      titulo.setFont(new java.awt.Font("Leelawadee", 0, 36)); // NOI18N
      titulo.setForeground(new java.awt.Color(0, 0, 0));
      titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      titulo.setText("Compra");

      javax.swing.GroupLayout northLayout = new javax.swing.GroupLayout(north);
      north.setLayout(northLayout);
      northLayout.setHorizontalGroup(
         northLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(northLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
            .addContainerGap())
      );
      northLayout.setVerticalGroup(
         northLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(northLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addContainerGap())
      );

      getContentPane().add(north, java.awt.BorderLayout.NORTH);

      south.setPreferredSize(new java.awt.Dimension(700, 50));

      novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
      novo.setText("Novo");
      novo.setPreferredSize(new java.awt.Dimension(120, 30));
      south.add(novo);

      cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
      cancelar.setText("Cancelar");
      cancelar.setEnabled(false);
      cancelar.setPreferredSize(new java.awt.Dimension(120, 30));
      south.add(cancelar);

      gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar2.png"))); // NOI18N
      gravar.setText("Gravar");
      gravar.setEnabled(false);
      gravar.setPreferredSize(new java.awt.Dimension(120, 30));
      south.add(gravar);

      buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
      buscar.setText("Buscar");
      buscar.setPreferredSize(new java.awt.Dimension(120, 30));
      south.add(buscar);

      sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
      sair.setText("Sair");
      sair.setPreferredSize(new java.awt.Dimension(120, 30));
      south.add(sair);

      getContentPane().add(south, java.awt.BorderLayout.SOUTH);

      fornecedor.setText("Fornecedor:");

      quantidade4.setText("Quantidade:");

      produto4.setText("Produto 4:");

      produto3.setText("Produto 3:");

      quantidade3.setText("Quantidade:");

      botaoPago.setText("RECEBIMENTO");

      quantidade2.setText("Quantidade:");

      produto2.setText("Produto 2:");

      qtdNumero1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            qtdNumero1ActionPerformed(evt);
         }
      });

      quantidade1.setText("Quantidade:");

      produto1.setText("Produto 1:");

      javax.swing.GroupLayout centerLayout = new javax.swing.GroupLayout(center);
      center.setLayout(centerLayout);
      centerLayout.setHorizontalGroup(
         centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(centerLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(centerLayout.createSequentialGroup()
                  .addGap(241, 241, 241)
                  .addComponent(botaoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addContainerGap(253, Short.MAX_VALUE))
               .addGroup(centerLayout.createSequentialGroup()
                  .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(centerLayout.createSequentialGroup()
                        .addComponent(fornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listaFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                     .addGroup(centerLayout.createSequentialGroup()
                        .addComponent(produto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listaProduto1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(quantidade1)
                        .addGap(11, 11, 11)
                        .addComponent(qtdNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerLayout.createSequentialGroup()
                        .addComponent(produto2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listaProduto2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(quantidade2)
                        .addGap(11, 11, 11)
                        .addComponent(qtdNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerLayout.createSequentialGroup()
                        .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addGroup(centerLayout.createSequentialGroup()
                              .addComponent(produto4)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(listaProduto4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                           .addGroup(centerLayout.createSequentialGroup()
                              .addComponent(produto3)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(listaProduto3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addGroup(centerLayout.createSequentialGroup()
                              .addComponent(quantidade3)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(qtdNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(centerLayout.createSequentialGroup()
                              .addComponent(quantidade4)
                              .addGap(11, 11, 11)
                              .addComponent(qtdNumero4)))))
                  .addContainerGap())))
      );
      centerLayout.setVerticalGroup(
         centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(centerLayout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(fornecedor)
               .addComponent(listaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(produto1)
               .addComponent(listaProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(quantidade1)
               .addComponent(qtdNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(produto2)
               .addComponent(listaProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(quantidade2)
               .addComponent(qtdNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(produto3)
               .addComponent(listaProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(quantidade3)
               .addComponent(qtdNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(produto4)
                  .addComponent(quantidade4)
                  .addComponent(qtdNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(listaProduto4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(botaoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(26, Short.MAX_VALUE))
      );

      getContentPane().add(center, java.awt.BorderLayout.CENTER);

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void qtdNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdNumero1ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_qtdNumero1ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(TelaCadastroCompraV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(TelaCadastroCompraV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(TelaCadastroCompraV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(TelaCadastroCompraV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>
      //</editor-fold>
      //</editor-fold>
      //</editor-fold>
      //</editor-fold>
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new TelaCadastroCompraV1().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton botaoPago;
   private javax.swing.JButton buscar;
   private javax.swing.JButton cancelar;
   private javax.swing.JPanel center;
   private javax.swing.JLabel fornecedor;
   private javax.swing.JButton gravar;
   private javax.swing.JComboBox<String> listaFornecedor;
   private javax.swing.JComboBox<String> listaProduto1;
   private javax.swing.JComboBox<String> listaProduto2;
   private javax.swing.JComboBox<String> listaProduto3;
   private javax.swing.JComboBox<String> listaProduto4;
   private javax.swing.JPanel north;
   private javax.swing.JButton novo;
   private javax.swing.JLabel produto1;
   private javax.swing.JLabel produto2;
   private javax.swing.JLabel produto3;
   private javax.swing.JLabel produto4;
   private javax.swing.JTextField qtdNumero1;
   private javax.swing.JTextField qtdNumero2;
   private javax.swing.JTextField qtdNumero3;
   private javax.swing.JTextField qtdNumero4;
   private javax.swing.JLabel quantidade1;
   private javax.swing.JLabel quantidade2;
   private javax.swing.JLabel quantidade3;
   private javax.swing.JLabel quantidade4;
   private javax.swing.JButton sair;
   private javax.swing.JPanel south;
   private javax.swing.JLabel titulo;
   // End of variables declaration//GEN-END:variables

   public JButton getBuscar() {
      return buscar;
   }

   public JButton getCancelar() {
      return cancelar;
   }

   public JButton getGravar() {
      return gravar;
   }

   public JButton getNovo() {
      return novo;
   }

   public JButton getSair() {
      return sair;
   }

   public JPanel getCenter() {
      return center;
   }

   public JButton getBotaoPago() {
      return botaoPago;
   }

   public JComboBox<String> getListaFornecedor() {
      return listaFornecedor;
   }

   public JComboBox<String> getListaProduto1() {
      return listaProduto1;
   }

   public JComboBox<String> getListaProduto2() {
      return listaProduto2;
   }

   public JComboBox<String> getListaProduto3() {
      return listaProduto3;
   }

   public JComboBox<String> getListaProduto4() {
      return listaProduto4;
   }

   public JTextField getQtdNumero1() {
      return qtdNumero1;
   }

   public JTextField getQtdNumero2() {
      return qtdNumero2;
   }

   public JTextField getQtdNumero3() {
      return qtdNumero3;
   }

   public JTextField getQtdNumero4() {
      return qtdNumero4;
   }
   
   
}
