/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.telasCadastro;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import jtextfields.Limitador;

/**
 *
 * @author julia
 */
public class TelaCadastroVenda extends javax.swing.JFrame {
   
   float valor;

   /**
    * Creates new form FormModeloCadastros
    */
   public TelaCadastroVenda() {
      initComponents();
      textoDesconto.setDocument(new Limitador(3));
      textoDescontoCents.setDocument(new Limitador(2));
      textoAcrescimo.setDocument(new Limitador(3));
      textoAcrescimoCents.setDocument(new Limitador(2));
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      north = new javax.swing.JPanel();
      titulo = new javax.swing.JLabel();
      south = new javax.swing.JPanel();
      novo = new javax.swing.JButton();
      cancelar = new javax.swing.JButton();
      gravar = new javax.swing.JButton();
      buscar = new javax.swing.JButton();
      sair = new javax.swing.JButton();
      center = new javax.swing.JPanel();
      aluno = new javax.swing.JLabel();
      listaAluno = new javax.swing.JComboBox<>();
      personal = new javax.swing.JLabel();
      listaPersonal = new javax.swing.JComboBox<>();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTable1 = new javax.swing.JTable();
      delete = new javax.swing.JButton();
      adicionar = new javax.swing.JButton();
      obs = new javax.swing.JLabel();
      textoObs = new javax.swing.JTextField();
      itens = new javax.swing.JLabel();
      valorTotal = new javax.swing.JLabel();
      textoValorTotal = new javax.swing.JTextField();
      textoAcrescimoCents = new javax.swing.JTextField();
      textoAcrescimo = new javax.swing.JTextField();
      acrescimo = new javax.swing.JLabel();
      desconto = new javax.swing.JLabel();
      textoDesconto = new javax.swing.JTextField();
      textoDescontoCents = new javax.swing.JTextField();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Formulário de Cadastro");
      setResizable(false);

      north.setBackground(new java.awt.Color(255, 204, 0));
      north.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      north.setPreferredSize(new java.awt.Dimension(700, 75));

      titulo.setFont(new java.awt.Font("Leelawadee", 0, 36)); // NOI18N
      titulo.setForeground(new java.awt.Color(0, 0, 0));
      titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      titulo.setText("VENDA");

      javax.swing.GroupLayout northLayout = new javax.swing.GroupLayout(north);
      north.setLayout(northLayout);
      northLayout.setHorizontalGroup(
         northLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(northLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
            .addContainerGap())
      );
      northLayout.setVerticalGroup(
         northLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(northLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addContainerGap())
      );

      getContentPane().add(north, java.awt.BorderLayout.NORTH);

      south.setPreferredSize(new java.awt.Dimension(700, 50));

      novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
      novo.setText("Novo");
      novo.setPreferredSize(new java.awt.Dimension(120, 30));
      south.add(novo);

      cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
      cancelar.setText("Cancelar");
      cancelar.setEnabled(false);
      cancelar.setPreferredSize(new java.awt.Dimension(120, 30));
      south.add(cancelar);

      gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar2.png"))); // NOI18N
      gravar.setText("Gravar");
      gravar.setEnabled(false);
      gravar.setPreferredSize(new java.awt.Dimension(120, 30));
      south.add(gravar);

      buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
      buscar.setText("Buscar");
      buscar.setPreferredSize(new java.awt.Dimension(120, 30));
      south.add(buscar);

      sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
      sair.setText("Sair");
      sair.setPreferredSize(new java.awt.Dimension(120, 30));
      south.add(sair);

      getContentPane().add(south, java.awt.BorderLayout.SOUTH);

      aluno.setText("Aluno:");

      personal.setText("Personal:");

      jTable1.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {
            "PRODUTO", "QTD", "SUBTOTAL"
         }
      ));
      jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
         public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            jTable1AncestorAdded(evt);
         }
         public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
         }
         public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
         }
      });
      jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
         }
      });
      jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
         public void componentShown(java.awt.event.ComponentEvent evt) {
            jTable1ComponentShown(evt);
         }
      });
      jScrollPane1.setViewportView(jTable1);
      if (jTable1.getColumnModel().getColumnCount() > 0) {
         jTable1.getColumnModel().getColumn(1).setMaxWidth(500);
      }

      delete.setText("DELETAR");

      adicionar.setText("ADICIONAR");

      obs.setText("Observações:");

      itens.setText("Itens:");

      valorTotal.setText("Valor Total:");

      textoValorTotal.setEnabled(false);

      acrescimo.setText("Acréscimo:");

      desconto.setText("Desconto:");

      javax.swing.GroupLayout centerLayout = new javax.swing.GroupLayout(center);
      center.setLayout(centerLayout);
      centerLayout.setHorizontalGroup(
         centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(centerLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(centerLayout.createSequentialGroup()
                  .addComponent(aluno)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(listaAluno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(centerLayout.createSequentialGroup()
                  .addComponent(personal)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(listaPersonal, 0, 583, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerLayout.createSequentialGroup()
                  .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(textoObs)
                     .addGroup(centerLayout.createSequentialGroup()
                        .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(obs)
                           .addGroup(centerLayout.createSequentialGroup()
                              .addComponent(valorTotal)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(textoValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(centerLayout.createSequentialGroup()
                              .addComponent(desconto)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(textoDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(textoDescontoCents, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(centerLayout.createSequentialGroup()
                              .addComponent(acrescimo)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(textoAcrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(textoAcrescimoCents, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                  .addGap(18, 18, 18)
                  .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(centerLayout.createSequentialGroup()
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(itens))))
            .addContainerGap())
      );
      centerLayout.setVerticalGroup(
         centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(centerLayout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(aluno)
               .addComponent(listaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(personal)
               .addComponent(listaPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(centerLayout.createSequentialGroup()
                  .addComponent(itens)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(centerLayout.createSequentialGroup()
                  .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(desconto)
                     .addComponent(textoDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(textoDescontoCents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(18, 18, 18)
                  .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(acrescimo)
                     .addComponent(textoAcrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(textoAcrescimoCents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(18, 18, 18)
                  .addComponent(obs)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(textoObs)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(valorTotal)
                  .addComponent(textoValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(24, Short.MAX_VALUE))
      );

      getContentPane().add(center, java.awt.BorderLayout.CENTER);

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      if(jTable1.getSelectedRowCount() > 0){
         delete.setEnabled(true);
      }
   }//GEN-LAST:event_jTable1MouseClicked

   private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
      
   }//GEN-LAST:event_jTable1ComponentShown

   private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
      for(int x = 0; x < jTable1.getRowCount(); x++){
         //valor += Float.parseFloat(jTable1.getValueAt(2, x).toString());
         System.out.println(jTable1.getValueAt(2, x).toString());
      }
   }//GEN-LAST:event_jTable1AncestorAdded

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(TelaCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(TelaCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(TelaCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(TelaCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new TelaCadastroVenda().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel acrescimo;
   private javax.swing.JButton adicionar;
   private javax.swing.JLabel aluno;
   private javax.swing.JButton buscar;
   private javax.swing.JButton cancelar;
   private javax.swing.JPanel center;
   private javax.swing.JButton delete;
   private javax.swing.JLabel desconto;
   private javax.swing.JButton gravar;
   private javax.swing.JLabel itens;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable jTable1;
   private javax.swing.JComboBox<String> listaAluno;
   private javax.swing.JComboBox<String> listaPersonal;
   private javax.swing.JPanel north;
   private javax.swing.JButton novo;
   private javax.swing.JLabel obs;
   private javax.swing.JLabel personal;
   private javax.swing.JButton sair;
   private javax.swing.JPanel south;
   private javax.swing.JTextField textoAcrescimo;
   private javax.swing.JTextField textoAcrescimoCents;
   private javax.swing.JTextField textoDesconto;
   private javax.swing.JTextField textoDescontoCents;
   private javax.swing.JTextField textoObs;
   private javax.swing.JTextField textoValorTotal;
   private javax.swing.JLabel titulo;
   private javax.swing.JLabel valorTotal;
   // End of variables declaration//GEN-END:variables

   public JButton getBuscar() {
      return buscar;
   }

   public JButton getCancelar() {
      return cancelar;
   }

   public JButton getGravar() {
      return gravar;
   }

   public JButton getNovo() {
      return novo;
   }

   public JButton getSair() {
      return sair;
   }

   public JPanel getCenter() {
      return center;
   }

   public JComboBox<String> getListaAluno() {
      return listaAluno;
   }

   public JComboBox<String> getListaPersonal() {
      return listaPersonal;
   }

   public JTable getjTable1() {
      return jTable1;
   }

   public JButton getAdicionar() {
      return adicionar;
   }

   public JButton getDelete() {
      return delete;
   }

   public JTextField getTextoObs() {
      return textoObs;
   }

   public JTextField getTextoValorTotal() {
      return textoValorTotal;
   }
   
   public JTextField getTextoAcrescimo() {
      return textoAcrescimo;
   }

   public JTextField getTextoAcrescimoCents() {
      return textoAcrescimoCents;
   }

   public JTextField getTextoDesconto() {
      return textoDesconto;
   }

   public JTextField getTextoDescontoCents() {
      return textoDescontoCents;
   }
}
